theme: jekyll-theme-slate

title: "Valentine: Evaluating Matching Techniques for Dataset Discovery"
description: "Webpage containing information on Delft-Data's Valentine paper"

show_downloads: false
